console.log("Estado del héroe");
const nombre = "ramon";
console.log(`Nombre: ${nombre}`);
let nivel = 5;
console.log(`Nivel: ${nivel}`);
let vida = 100;
console.log(`Puntos de vida: ${vida}`);
const arma_principal = "Espada del destino";
console.log(`Arma principal: ${arma_principal}`);
const arma_secundaria = "arco simple";
console.log(`Arma secundaria: ${arma_secundaria}`);
let armadura = true;
console.log(`Tiene armadura: ${armadura}`);
console.log();
console.log("Estado del héroe después del combate:");
console.log(`Nombre: ${nombre}`);
nivel += 1;
console.log(`Nivel: ${nivel}`);
vida -= 30;
console.log(`Puntos de vida: ${vida}`);